ERROR:root:<class 'Exception'>
Traceback (most recent call last):
  File "c:\Users\vikto\Documents\Old computer files\SFA\Scramble_for_Africa.py", line 35, in <module>
    main_loop.main_loop(global_manager)
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\main_loop.py", line 193, in main_loop
    main_loop_tools.update_display(global_manager)
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\main_loop_tools.py", line 61, in update_display
    current_image.draw()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\images.py", line 1064, in draw
    if self.button.can_show():
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\dice.py", line 224, in can_show
    num_notification_dice = self.global_manager.get('notification_list')[0].notification_dice
IndexError: list index out of range
