ERROR:root:'no_canoes_image'
Traceback (most recent call last):
  File "C:\Users\vikto\Documents\Old computer files\SFA\Scramble_for_Africa.py", line 995, in <module>
    main_loop.main_loop(global_manager)
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\main_loop.py", line 171, in main_loop
    current_button.on_click()
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\buttons.py", line 852, in on_click
    self.global_manager.get('save_load_manager').save_game('save1.pickle')
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\save_load_tools.py", line 209, in save_game
    saved_grid_dicts.append(current_grid.to_save_dict())
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\grids.py", line 104, in to_save_dict
    save_dict['cell_list'].append(current_cell.to_save_dict())
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\cells.py", line 96, in to_save_dict
    save_dict['village_attached_warriors'].append(attached_warrior.to_save_dict())
  File "C:\Users\vikto\Documents\Old computer files\SFA\modules\mobs.py", line 115, in to_save_dict
    save_dict['image'] = self.image_dict['no_canoes_image']
KeyError: 'no_canoes_image'
