ERROR:root:<class 'Exception'>
Traceback (most recent call last):
  File "c:\Users\vikto\Documents\Old computer files\SFA\Scramble_for_Africa.py", line 35, in <module>
    main_loop.main_loop(global_manager)
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\main_loop.py", line 161, in main_loop
    current_button.on_click()#prioritize clicking buttons that appear above other buttons and don't press the ones
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\choice_notifications.py", line 200, in on_click
    super().on_click()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\buttons.py", line 1052, in on_click
    battalion.capture_slaves()
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\mob_types\group_types\battalions.py", line 314, in capture_slaves
    self.controlling_minister.steal_money(self.global_manager.get('action_prices')['slave_capture'], 'slave_capture')
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\ministers.py", line 165, in steal_money
    evidence_message += self.global_manager.get('transaction_descriptions')[theft_type] + ' and has filed a piece of evidence against him. /n /n'
KeyError: 'slave capture'
