ERROR:root:<class 'Exception'>
Traceback (most recent call last):
  File "c:\Users\vikto\Documents\Old computer files\SFA\Scramble_for_Africa.py", line 9, in <module>
    setup.fundamental_setup(global_manager)
  File "c:\Users\vikto\Documents\Old computer files\SFA\modules\setup.py", line 59, in fundamental_setup
    global_manager.set('default_font_size', 15, global_manager)
TypeError: global_manager_template.set() takes 3 positional arguments but 4 were given
